# Generated by Django 4.1.7 on 2023-03-12 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=250, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
        migrations.CreateModel(
            name='Fachrichtung',
            fields=[
                ('kategorie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kategorie')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung')),
                ('kunde', models.CharField(blank=True, max_length=255, verbose_name='Kunde')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Fachrichtung',
                'verbose_name_plural': 'Fachrichtungen',
                'ordering': ['kategorie'],
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Name')),
                ('mail', models.CharField(blank=True, max_length=250, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
            },
        ),
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostentraeger', models.CharField(max_length=250, unique=True, verbose_name='Geschäftsfeld/Kostenträger')),
                ('anmerkung', models.CharField(blank=True, max_length=250, verbose_name='Anmerkung')),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
                'ordering': ['kostentraeger'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('bezeichnung', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Organisation')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
            },
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.CharField(max_length=250, unique=True, verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagworte',
                'verbose_name_plural': 'Schlagwort',
                'ordering': ['schlagwort'],
            },
        ),
        migrations.CreateModel(
            name='Vorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorschlag', models.CharField(max_length=50, verbose_name='Vorschlag')),
                ('begruendung', models.TextField(verbose_name='Begründung')),
                ('vorschlagdatum', models.DateField(auto_now_add=True, verbose_name='vorgeschlagen am')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Vorschlag',
                'verbose_name_plural': 'Vorschläge',
            },
        ),
        migrations.CreateModel(
            name='Vorschlagbearbeitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmerkung', models.TextField(verbose_name='Anmerkung')),
                ('erledigt', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('vorschlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.vorschlag', verbose_name='Vorschlag')),
            ],
            options={
                'verbose_name': 'V.Bearbeitung',
                'verbose_name_plural': 'V.Bearbeitungen',
            },
        ),
        migrations.CreateModel(
            name='Reha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahmentitel', models.TextField(verbose_name='Maßnahmentitel')),
                ('abrechnungsart', models.CharField(max_length=50, verbose_name='Abrechnungsart')),
                ('dauer', models.CharField(max_length=50, verbose_name='Dauer')),
                ('praxisdauer', models.CharField(max_length=50, verbose_name='Praxisdauer')),
                ('abschluss', models.TextField(blank=True, verbose_name='Abschluss')),
                ('schlagrichtung', models.TextField(verbose_name='inhalt. Schlagrichtung')),
                ('status', models.BooleanField(verbose_name='aktiv')),
                ('dokumente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.dokument', verbose_name='Dokumente')),
                ('fachrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.fachrichtung', verbose_name='Fachrrichtung')),
                ('kostentraeger', models.ManyToManyField(to='bfwnetzwerk.kostentraeger', verbose_name='Geschäftfeld/Kostenträger')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.organisation', verbose_name='Organisation')),
                ('schlagwort', models.ManyToManyField(to='bfwnetzwerk.schlagwort', verbose_name='Schlagwort')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Maßnahmenverantwortlicher')),
            ],
            options={
                'verbose_name': 'Reha',
                'verbose_name_plural': 'Rehas',
            },
        ),
    ]
