# Generated by Django 4.1.7 on 2023-02-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=250, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name_plural': 'Dokumente',
            },
        ),
        migrations.CreateModel(
            name='Fachrichtung',
            fields=[
                ('kategorie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kategorie')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('kunde', models.CharField(max_length=255, verbose_name='Kunde')),
                ('aktiv', models.BooleanField(verbose_name='Aktiv')),
            ],
            options={
                'verbose_name_plural': 'Fachrichtungen',
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('mail', models.CharField(max_length=250, verbose_name='E-Mail')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
            options={
                'verbose_name_plural': 'Kontakte',
            },
        ),
        migrations.CreateModel(
            name='Reha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahmentitel', models.CharField(max_length=255, verbose_name='Maßnahmentitel')),
                ('schlagrichtung', models.TextField(verbose_name='inhalt. Schlagrichtung')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('fachrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.fachrichtung', verbose_name='Fachrrichtung')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Maßnahmenverantwortlicher')),
            ],
            options={
                'verbose_name_plural': 'Rehas',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Organisation')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner')),
            ],
        ),
    ]
