# Generated by Django 4.1.7 on 2023-02-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=250, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
        migrations.CreateModel(
            name='Fachrichtung',
            fields=[
                ('kategorie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kategorie')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung')),
                ('kunde', models.CharField(blank=True, max_length=255, verbose_name='Kunde')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Fachrichtung',
                'verbose_name_plural': 'Fachrichtungen',
                'ordering': ['kategorie'],
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Name')),
                ('mail', models.CharField(blank=True, max_length=250, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
            },
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.CharField(max_length=50, unique=True, verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagworte',
                'verbose_name_plural': 'Schlagwort',
                'ordering': ['schlagwort'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('bezeichnung', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Organisation')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
            },
        ),
    ]
