# Generated by Django 4.1.7 on 2023-02-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostentraeger', models.CharField(max_length=250, verbose_name='Geschäftsfeld/Kostenträger')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner')),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
                'ordering': ['kostentraeger'],
            },
        ),
        migrations.CreateModel(
            name='Reha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahmentitel', models.TextField(verbose_name='Maßnahmentitel')),
                ('abrechnungsart', models.CharField(max_length=50, verbose_name='Abrechnungsart')),
                ('dauer', models.CharField(max_length=50, verbose_name='Abrechnungsart')),
                ('praxisdauer', models.CharField(max_length=50, verbose_name='Praxisdauer')),
                ('abschluss', models.TextField(blank=True, verbose_name='Abschluss')),
                ('schlagrichtung', models.TextField(verbose_name='inhalt. Schlagrichtung')),
                ('status', models.BooleanField(verbose_name='aktiv')),
                ('dokumente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.dokument', verbose_name='Dokumente')),
                ('fachrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.fachrichtung', verbose_name='Fachrrichtung')),
                ('kostentraeger', models.ManyToManyField(to='bfwnetzwerk.kostentraeger', verbose_name='Geschäftfeld/Kostenträger')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.organisation', verbose_name='Organisation')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Maßnahmenverantwortlicher')),
            ],
            options={
                'verbose_name': 'Reha',
                'verbose_name_plural': 'Rehas',
            },
        ),
    ]
