# Generated by Django 4.1.7 on 2023-02-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reha',
            name='organisation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
    ]
