# Generated by Django 4.1.7 on 2023-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0002_reha_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='mail',
            field=models.CharField(blank=True, max_length=250, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
    ]
