# Generated by Django 4.1.7 on 2023-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0002_kostentraeger_reha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reha',
            name='schlagwort',
            field=models.ManyToManyField(to='bfwnetzwerk.schlagwort', verbose_name='Schlagwort'),
        ),
    ]
