# Generated by Django 4.1.7 on 2023-02-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0002_alter_kostentraeger_kostentraeger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kostentraeger',
            name='ansprechpartner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner'),
        ),
    ]
