# Generated by Django 4.1.7 on 2023-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0003_alter_kostentraeger_ansprechpartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kostentraeger',
            name='ansprechpartner',
        ),
        migrations.AddField(
            model_name='kostentraeger',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=250, verbose_name='Anmerkung'),
        ),
    ]
