# Generated by Django 4.1.7 on 2023-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0003_alter_kontakt_mail_alter_kontakt_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.CharField(max_length=50, verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagworte',
                'verbose_name_plural': 'Schlagwort',
            },
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name_plural': 'Organisationen'},
        ),
        migrations.AlterModelOptions(
            name='reha',
            options={'verbose_name': 'Reha', 'verbose_name_plural': 'Rehas'},
        ),
        migrations.AlterField(
            model_name='reha',
            name='massnahmentitel',
            field=models.TextField(verbose_name='Maßnahmentitel'),
        ),
    ]
