# Generated by Django 4.1.7 on 2023-02-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0004_schlagwort_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='fachrichtung',
            options={'verbose_name': 'Fachrichtung', 'verbose_name_plural': 'Fachrichtungen'},
        ),
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakte'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisationen'},
        ),
        migrations.AlterModelOptions(
            name='schlagwort',
            options={'ordering': ['schlagwort'], 'verbose_name': 'Schlagworte', 'verbose_name_plural': 'Schlagwort'},
        ),
        migrations.CreateModel(
            name='SchlagwortReha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.reha', verbose_name='Reha')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.schlagwort', verbose_name='SSchlagwort/Reha')),
            ],
            options={
                'verbose_name': 'Schlagwort/Reha',
                'verbose_name_plural': 'Schlagworter/Reha',
            },
        ),
    ]
