# Generated by Django 4.1.7 on 2023-02-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0005_alter_dokument_options_alter_fachrichtung_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schlagwortreha',
            options={'ordering': ['reha'], 'verbose_name': 'Schlagwort/Reha', 'verbose_name_plural': 'Schlagworter/Reha'},
        ),
        migrations.AddField(
            model_name='reha',
            name='dokumente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.dokument', verbose_name='Dokumente'),
            preserve_default=False,
        ),
    ]
