# Generated by Django 4.1.7 on 2023-03-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0005_vorschlaege_alter_reha_dauer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vorschlaege',
            new_name='Vorschlag',
        ),
    ]
