# Generated by Django 4.1.7 on 2023-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0006_alter_schlagwortreha_options_reha_dokumente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reha',
            name='dokumente',
        ),
    ]
