# Generated by Django 4.1.7 on 2023-03-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0006_rename_vorschlaege_vorschlag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vorschlag',
            name='bearbeitet',
        ),
        migrations.RemoveField(
            model_name='vorschlag',
            name='erledigt',
        ),
        migrations.RemoveField(
            model_name='vorschlag',
            name='kommentar',
        ),
    ]
