# Generated by Django 4.1.7 on 2023-03-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0007_remove_vorschlag_bearbeitet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorschlagbearbeitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmerkung', models.TextField(verbose_name='Anmerkung')),
                ('erledigt', models.BooleanField(default=True, verbose_name='Erledigt')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('vorschlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.vorschlag', verbose_name='Vorschlag')),
            ],
            options={
                'verbose_name': 'Bearbeitung',
                'verbose_name_plural': 'Bearbeitungen',
            },
        ),
    ]
