# Generated by Django 4.1.7 on 2023-03-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0008_vorschlagbearbeitung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vorschlagbearbeitung',
            options={'verbose_name': 'V.Bearbeitung', 'verbose_name_plural': 'V.Bearbeitungen'},
        ),
    ]
