# Generated by Django 4.1.7 on 2023-03-03 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfwnetzwerk', '0009_alter_vorschlagbearbeitung_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorschlag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vorschlagbearbeitung',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
            preserve_default=False,
        ),
    ]
