# Generated by Django 4.1.7 on 2023-02-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0009_remove_reha_dokumente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reha',
            name='dokumente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.dokument', verbose_name='Dokumente'),
            preserve_default=False,
        ),
    ]
