# Generated by Django 4.1.7 on 2023-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0010_reha_dokumente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reha',
            name='schlagwort',
            field=models.ManyToManyField(to='bfwnetzwerk.schlagwort', verbose_name='Schlagwort'),
        ),
    ]
