# Generated by Django 4.1.7 on 2023-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bfwnetzwerk", "0011_alter_vorschlag_user_alter_vorschlagbearbeitung_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vorschlagbearbeitung",
            name="erledigt",
            field=models.BooleanField(default=False, verbose_name="Erledigt"),
        ),
    ]
