# Generated by Django 4.1.7 on 2023-02-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0011_reha_schlagwort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostentraeger', models.CharField(max_length=250, verbose_name='Geschäftsfeld/Kostenträger')),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
                'ordering': ['kostentraeger'],
            },
        ),
    ]
