# Generated by Django 4.1.7 on 2023-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0012_alter_vorschlagbearbeitung_erledigt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reha',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.RemoveField(
            model_name='reha',
            name='verantwortlicher',
        ),
        migrations.AddField(
            model_name='organisation',
            name='ansprechpartner2',
            field=models.CharField(default=' ', max_length=100, verbose_name='Ansprechpartner2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='ansprechpartner2_mail',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ansprechpartner2 Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='ansprechpartner2_telefon',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ansprechpartner2 Telefon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='ansprechpartner_mail',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ansprechpartner Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='ansprechpartner_telefon',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ansprechpartner Telefon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner',
            field=models.CharField(max_length=100, verbose_name='Ansprechpartner'),
        ),
        migrations.AlterField(
            model_name='reha',
            name='dokumente',
            field=models.URLField(verbose_name='Dokument'),
        ),
        migrations.DeleteModel(
            name='Dokument',
        ),
        migrations.DeleteModel(
            name='Kontakt',
        ),
    ]
