# Generated by Django 4.1.7 on 2023-02-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0012_kostentraeger'),
    ]

    operations = [
        migrations.AddField(
            model_name='kostentraeger',
            name='ansprechpartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner'),
        ),
    ]
