# Generated by Django 4.1.7 on 2023-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0013_alter_reha_options_remove_reha_verantwortlicher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ansprechpartner2'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2_mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ansprechpartner2 Mail'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2_telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ansprechpartner2 Telefon'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner_mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ansprechpartner Mail'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner_telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ansprechpartner Telefon'),
        ),
    ]
