# Generated by Django 4.1.7 on 2023-02-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0014_reha_kostentraeger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reha',
            name='kostentraeger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kostentraeger', verbose_name='Geschäftfeld/Kostenträger'),
            preserve_default=False,
        ),
    ]
