# Generated by Django 4.1.7 on 2023-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0014_alter_organisation_ansprechpartner2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reha',
            name='fachrichtung',
        ),
        migrations.AddField(
            model_name='reha',
            name='fachrichtung',
            field=models.ManyToManyField(blank=True, to='bfwnetzwerk.fachrichtung', verbose_name='Produkt(e)'),
        ),
    ]
