# Generated by Django 4.1.7 on 2023-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0015_remove_reha_fachrichtung_reha_fachrichtung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massnahmeart',
            fields=[
                ('art', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kategorie')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Maßnahmeart',
                'verbose_name_plural': 'Maßnahmearten',
                'ordering': ['art'],
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahmentitel', models.TextField(verbose_name='Maßnahmentitel')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.RenameModel(
            old_name='Kostentraeger',
            new_name='Abrechnungsart',
        ),
        migrations.RemoveField(
            model_name='reha',
            name='fachrichtung',
        ),
        migrations.RemoveField(
            model_name='reha',
            name='kostentraeger',
        ),
        migrations.RemoveField(
            model_name='reha',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='reha',
            name='schlagwort',
        ),
        migrations.RemoveField(
            model_name='vorschlag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vorschlagbearbeitung',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vorschlagbearbeitung',
            name='vorschlag',
        ),
        migrations.AlterModelOptions(
            name='abrechnungsart',
            options={'ordering': ['kunde'], 'verbose_name': 'Produkt / Abrechnungsart', 'verbose_name_plural': 'Produkte / Abrechnungsart'},
        ),
        migrations.RenameField(
            model_name='abrechnungsart',
            old_name='kostentraeger',
            new_name='kunde',
        ),
        migrations.DeleteModel(
            name='Fachrichtung',
        ),
        migrations.DeleteModel(
            name='Reha',
        ),
        migrations.DeleteModel(
            name='Vorschlag',
        ),
        migrations.DeleteModel(
            name='Vorschlagbearbeitung',
        ),
    ]
