# Generated by Django 4.1.7 on 2023-02-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0015_alter_reha_kostentraeger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kostentraeger',
            name='ansprechpartner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfwnetzwerk.kontakt', verbose_name='Ansprechpartner'),
            preserve_default=False,
        ),
    ]
