# Generated by Django 4.1.7 on 2023-05-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0016_massnahmeart_produkt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostentraeger', models.CharField(max_length=80, verbose_name='Kostenträger')),
                ('anmerkung', models.TextField(verbose_name='Anmerkung')),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
            },
        ),
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahmentitel', models.TextField(verbose_name='Maßnahmentitel')),
                ('schlagrichtung', models.TextField(verbose_name='Inhaltliche Schlagrichtung')),
                ('dauer', models.CharField(max_length=50, verbose_name='Dauer')),
                ('praxisdauer', models.CharField(blank=True, max_length=50, verbose_name='Praxisdauer')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('dokument', models.URLField(verbose_name='Dokument')),
                ('abrechnungsart', models.ManyToManyField(to='bfwnetzwerk.abrechnungsart', verbose_name='Produkt / Abrechnungsart')),
                ('kostentraeger', models.ManyToManyField(to='bfwnetzwerk.kostentraeger', verbose_name='Kostenträger')),
                ('massnahmeart', models.ManyToManyField(to='bfwnetzwerk.massnahmeart', verbose_name='Maßnahmeart')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bfwnetzwerk.organisation', verbose_name='Organisation')),
                ('schlagwoerter', models.ManyToManyField(to='bfwnetzwerk.schlagwort', verbose_name='Schlagwörter')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.DeleteModel(
            name='Produkt',
        ),
    ]
