# Generated by Django 4.1.7 on 2023-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0016_alter_kostentraeger_ansprechpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schlagwort',
            name='schlagwort',
            field=models.CharField(max_length=50, unique=True, verbose_name='Schlagwort'),
        ),
        migrations.DeleteModel(
            name='SchlagwortReha',
        ),
    ]
