# Generated by Django 4.1.7 on 2023-02-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0017_alter_schlagwort_schlagwort_delete_schlagwortreha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reha',
            name='kostentraeger',
        ),
        migrations.AddField(
            model_name='reha',
            name='kostentraeger',
            field=models.ManyToManyField(to='bfwnetzwerk.kostentraeger', verbose_name='Geschäftfeld/Kostenträger'),
        ),
    ]
