# Generated by Django 4.1.7 on 2023-05-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0018_produkt_delete_produkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='massnahmeart',
        ),
        migrations.AddField(
            model_name='produkt',
            name='massnahmeart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bfwnetzwerk.massnahmeart', verbose_name='Maßnahmenart'),
            preserve_default=False,
        ),
    ]
