# Generated by Django 4.1.7 on 2023-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0021_alter_abschluss_name_alter_massnahmeart_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrechnungsart',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='abschluss',
            name='bemerkung',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='kostentraeger',
            name='anmerkung',
            field=models.TextField(blank=True, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='massnahmeart',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ansprechpartner2'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2_mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ansprechpartner2 Mail'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner2_telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ansprechpartner2 Telefon'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner_mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ansprechpartner Mail'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ansprechpartner_telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ansprechpartner Telefon'),
        ),
    ]
