# Generated by Django 4.1.7 on 2023-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfwnetzwerk', '0022_alter_abrechnungsart_anmerkung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='praxisdauer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Praxisdauer'),
        ),
    ]
